server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
spring:
  elasticsearch:
    jest:
      connection-timeout: 30000
      multi-threaded: true
      uris: http://192.168.88.128:9200
      read-timeout: 7200
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
logging:
  level:
    root: error
    com.sleepy: info