spring:
  profiles:
    active: prod
  application:
    name: so-file-system-service
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
server:
  port: 9020
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:logback-spring.xml
  level:
    root: error
    com.sleepy: info