server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
spring:
  datasource:
    url: jdbc:mysql://mysql.sleepyocean.cn:8005/test?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
logging:
  level:
    root: error
    com.sleepy: info