server:
  port: 10020
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/dev?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  elasticsearch:
    rest:
      connection-timeout: 10s
      uris: http://192.168.200.128:9200
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
logging:
  level:
    root: error
    com.sleepy: info