server:
  port: 10020
  tomcat:
    uri-encoding: UTF-8
spring:
  elasticsearch:
    rest:
      connection-timeout: 10s
      uris: http://192.168.200.128:9200
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
logging:
  level:
    root: error
    com.sleepy: info