server:
  port: 9010
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://mysql.sleepyocean.cn:8000/so?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
  redis:
    host: redis.sleepyocean.cn
    port: 8015
    timeout: 3000
    jedis.pool:
      max-active: 8
      max-idle: 8
      min-idle: 2
logging:
  level:
    # 全局等级
    root: warn
    com:
      sleepy: info
  file:
    name: log\so-blog-server.log