server:
  port: 9010
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
  jpa:
    database: MYSQL
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
  redis:
    port: 8015
    timeout: 3000
    jedis.pool:
      max-active: 8
      max-idle: 8
      min-idle: 2
logging:
  config: classpath:logback-spring.xml
  level:
    # 全局等级
    root: warn
    com:
      sleepy: info